/* eslint-disable @typescript-eslint/no-require-imports, global-require */
import type { ImageSourcePropType } from 'react-native'

const PRODUCE_IMAGE_MAP = {
  abricot: require('../assets/produce/abricot.webp'),
  ail: require('../assets/produce/ail.webp'),
  artichaut: require('../assets/produce/artichaut.webp'),
  asperge: require('../assets/produce/asperge.webp'),
  aubergine: require('../assets/produce/aubergine.webp'),
  banane: require('../assets/produce/banane.webp'),
  betterave: require('../assets/produce/betterave.webp'),
  blette: require('../assets/produce/blette.webp'),
  brocoli: require('../assets/produce/brocoli.webp'),
  butternut: require('../assets/produce/butternut.webp'),
  carotte: require('../assets/produce/carotte.webp'),
  cassis: require('../assets/produce/cassis.webp'),
  'celeri-branche': require('../assets/produce/celeri-branche.webp'),
  'celeri-rave': require('../assets/produce/celeri-rave.webp'),
  cerise: require('../assets/produce/cerise.webp'),
  'champignon-de-paris': require('../assets/produce/champignon-de-paris.webp'),
  chataigne: require('../assets/produce/chataigne.webp'),
  'chou-chinois': require('../assets/produce/chou-chinois.webp'),
  'chou-de-bruxelles': require('../assets/produce/chou-de-bruxelles.webp'),
  'chou-fleur': require('../assets/produce/chou-fleur.webp'),
  'chou-kale': require('../assets/produce/chou-kale.webp'),
  'chou-rave': require('../assets/produce/chou-rave.webp'),
  'chou-rouge': require('../assets/produce/chou-rouge.webp'),
  'chou-vert': require('../assets/produce/chou-vert.webp'),
  citron: require('../assets/produce/citron.webp'),
  clementine: require('../assets/produce/clementine.webp'),
  concombre: require('../assets/produce/concombre.webp'),
  'courge-spaghetti': require('../assets/produce/courge-spaghetti.webp'),
  courgette: require('../assets/produce/courgette.webp'),
  cresson: require('../assets/produce/cresson.webp'),
  crosne: require('../assets/produce/crosne.webp'),
  echalote: require('../assets/produce/echalote.webp'),
  endive: require('../assets/produce/endive.webp'),
  epinard: require('../assets/produce/epinard.webp'),
  fenouil: require('../assets/produce/fenouil.webp'),
  feve: require('../assets/produce/feve.webp'),
  figue: require('../assets/produce/figue.webp'),
  fraise: require('../assets/produce/fraise.webp'),
  framboise: require('../assets/produce/framboise.webp'),
  grenade: require('../assets/produce/grenade.webp'),
  groseille: require('../assets/produce/groseille.webp'),
  'haricot-vert': require('../assets/produce/haricot-vert.webp'),
  kiwi: require('../assets/produce/kiwi.webp'),
  mache: require('../assets/produce/mache.webp'),
  mais: require('../assets/produce/mais.webp'),
  mandarine: require('../assets/produce/mandarine.webp'),
  melon: require('../assets/produce/melon.webp'),
  mirabelle: require('../assets/produce/mirabelle.webp'),
  mure: require('../assets/produce/mure.webp'),
  myrtille: require('../assets/produce/myrtille.webp'),
  navet: require('../assets/produce/navet.webp'),
  nectarine: require('../assets/produce/nectarine.webp'),
  noisette: require('../assets/produce/noisette.webp'),
  noix: require('../assets/produce/noix.webp'),
  oignon: require('../assets/produce/oignon.webp'),
  orange: require('../assets/produce/orange.webp'),
  pamplemousse: require('../assets/produce/pamplemousse.webp'),
  panais: require('../assets/produce/panais.webp'),
  pasteque: require('../assets/produce/pasteque.webp'),
  'patate-douce': require('../assets/produce/patate-douce.webp'),
  peche: require('../assets/produce/peche.webp'),
  'petit-pois': require('../assets/produce/petit-pois.webp'),
  poire: require('../assets/produce/poire.webp'),
  poireau: require('../assets/produce/poireau.webp'),
  poivron: require('../assets/produce/poivron.webp'),
  pomme: require('../assets/produce/pomme.webp'),
  'pomme-de-terre': require('../assets/produce/pomme-de-terre.webp'),
  potimarron: require('../assets/produce/potimarron.webp'),
  potiron: require('../assets/produce/potiron.webp'),
  prune: require('../assets/produce/prune.webp'),
  radis: require('../assets/produce/radis.webp'),
  'radis-noir': require('../assets/produce/radis-noir.webp'),
  raisin: require('../assets/produce/raisin.webp'),
  rhubarbe: require('../assets/produce/rhubarbe.webp'),
  roquette: require('../assets/produce/roquette.webp'),
  rutabaga: require('../assets/produce/rutabaga.webp'),
  salade: require('../assets/produce/salade.webp'),
  salsifis: require('../assets/produce/salsifis.webp'),
  tomate: require('../assets/produce/tomate.webp'),
  topinambour: require('../assets/produce/topinambour.webp')
} as const satisfies Record<string, ImageSourcePropType>

export type ProduceImageSlug = keyof typeof PRODUCE_IMAGE_MAP

export function getProduceImage(slug: ProduceImageSlug): ImageSourcePropType {
  return PRODUCE_IMAGE_MAP[slug]
}
